spring:
  application:
    name: logharbour
  kafka:
    consumer:
      bootstrap-servers: "localhost:9092"
      group-id: logger
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    producer:
      bootstrap-servers: "localhost:9092"
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
kafka:
  topic: logharbour

elasticsearch:
  username: elastic

  password: 6s9D_pkiKV1Djl5BXy-Z
  # 6s9D_pkiKV1Djl5BXy-Z
  host: localhost
  port: 9200
  scheme: https

logging:
  level:
    root: INFO
    "[com.remiges.logharbour]": DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
